version: '3'

services:
  master:
    image: quicklab:master
    build:
      context: .
      dockerfile: Dockerfile.master
    command: ["/usr/bin/salt-master","-l","debug"]
    privileged: True
    hostname: saltmaster
    privileged: True
    volumes: 
      - "./saltstack:/srv"
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks: 
      saltnet:
        aliases:
          - saltmaster
          - master

  minion:
    image: quicklab:minion
    build:
      context: .
      dockerfile: Dockerfile.minion
      args:
        masterip: saltmaster
    command: ["/usr/bin/salt-minion","-l","debug"]
    privileged: True
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      saltnet:

  
networks:
  saltnet:
      
